version: "3"
services:
  gamecon:
    build: .
    volumes:
      - .:/var/www/html/gamecon:delegated
    entrypoint: /.docker/xdebug.gamecon-run.sh
    ports:
      - 80:80

  sql.gamecon:
    image: mariadb:10.1
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 13306:3306
