version: "3"
services:
  gamecon:
    build: .
    volumes:
      - .:/var/www/html/gamecon:delegated
    command: sh -c "sudo -u www-data composer --working-dir=/var/www/html/gamecon install &&
      chgrp -R www-data /var/www/html/gamecon/cache && chmod -R g+rw /var/www/html/gamecon/cache &&
      chgrp -R www-data /var/www/html/gamecon/web/soubory/systemove/* && chmod -R g+rw /var/www/html/gamecon/web/soubory/systemove/* &&
      apache2-foreground"
    labels:
      - "traefik.frontend.rule=Host:gamecon.loc"
      - "traefik.docker.network=docker-www"
      - "traefik.docker.port=80"
    networks:
      - default
      - proxy

  sql.gamecon:
    image: mariadb:10.1
    environment:
      - MYSQL_ROOT_PASSWORD=root
    labels:
      - "traefik.backend=sql.gamecon"
      - "traefik.frontend.rule=Host:sql.gamecon.loc"
      - "traefik.docker.network=docker-www"
    ports:
      - 13306:3306
    networks:
      - default
      - proxy

networks:
  proxy:
    external:
      name: docker-www
