version: "3"
services:
  gamecon:
    build: .
    restart: "no"
    volumes:
      - .:/var/www/html/gamecon:delegated
      - ~/.cache/composer:/home/www/.composer
      - ./.docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-compose-xdebug.ini:ro
    environment:
      XDEBUG_CONFIG: "client_host=172.17.0.1 client_port=9003 remote_log=/tmp/xdebug.log"
    #      XDEBUG_TRIGGER: "yes" # to start XDebug for EVERY request (use `export XDEBUG_TRIGGER: "yes"` to enable it in CLI and `unset XDEBUG_TRIGGER` to disable for CLI again - in browser use same-named variable in GET, POST or COOKIE, or legacy named via some browser extension)
    ports:
      - 80:80

  sql.gamecon:
    image: mariadb:10.1
    restart: "no"
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ~/.cache/gamecon/mysql:/var/lib/mysql
    ports:
      - 13306:3306
