version: "3"
services:
  gamecon:
    build: .
    volumes:
      - .:/var/www/html/gamecon:delegated
    entrypoint:
      - sh
      - -c
      - head -n 1 /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini > /tmp/docker-php-ext-xdebug.ini && cat /tmp/docker-php-ext-xdebug.ini > /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini && echo "\nxdebug.remote_connect_back=1\nxdebug.remote_port=9000\nxdebug.remote_enable=1\nxdebug.idekey=PHPSTORM\nxdebug.remote_log=/tmp/xdebug.log" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini && echo 'http://gamecon.loc/gamecon/web http://gamecon.loc/gamecon/admin http://gamecon.loc/gamecon/adminer' && /.docker/gamecon-run.sh
    ports:
      - 888:80
    labels:
      - "traefik.backend=gamecon"
      - "traefik.frontend.rule=Host:gamecon.loc"
      - "traefik.docker.network=docker-www"
      - "traefik.docker.port=80"
    networks:
      - default
      - proxy

  sql.gamecon:
    image: mariadb:10.1
    environment:
      - MYSQL_ROOT_PASSWORD=root
    labels:
      - "traefik.backend=sql.gamecon"
      - "traefik.frontend.rule=Host:sql.gamecon.loc"
      - "traefik.docker.network=docker-www"
    ports:
      - 13306:3306
    networks:
      - default
      - proxy

networks:
  proxy:
    external:
      name: docker-www
